fps = 45
screen_width = 1200
screen_height = 800
default_background_color = [255,255,255] # white

[sprite]
path = 'assets\msedge_4IvGRozQp0.png'

[menu]
options = ["Continue", "Settings", "Exit"]

[settings]
options = ["Difficulty", "Background", "Character", "Theme"]

[font]
size = 200
path = 'assets\SunnySpellsBasicRegular-Yz1Wv.ttf'