fps = 60
screen_width = 2000
screen_height = 1600
default_background_color = [255,255,255] # white

[sprite]
path = 'assets\msedge_4IvGRozQp0.png'

[menu]
options = ["Continue", "Settings", "Exit"]

[settings]
options = ["Difficulty", "Movement speed"]

[font]
size = 200
path = 'assets\SunnySpellsBasicRegular-Yz1Wv.ttf'