fps = 45
screen_width = 1200
screen_height = 800
default_background_color = [255,255,255] # white

main_menu = ["New Game", "Settings", "Exit"]

menu = ["Continue", "Settings", "Exit"]

settings = ["Difficulty", "BGM", "Character", "Theme"]

difficulty = []

[sprite]
path = 'assets\msedge_4IvGRozQp0.png'

[font]
path = 'assets\SunnySpellsBasicRegular-Yz1Wv.ttf'