fps = 45
screen_width = 1200
screen_height = 800
default_background_color = [255,255,255] # white

[player]
HP = 10
path = 'assets\msedge_4IvGRozQp0.png'

[font]
path = 'assets\SunnySpellsBasicRegular-Yz1Wv.ttf'