[difficulty]
    [difficulty.0]
        algorithm = 'dfs'
        map_enlargement_scale = 1
        item_appearance_rate = 0.5
    [difficulty.1] 
        algorithm = 'dfs'
        map_enlargement_scale = 1.5
        item_appearance_rate = 0.4
    [difficulty.2]
        algorithm = 'dfs'
        map_enlargement_scale = 2
        item_appearance_rate = 0.3

[1]
map_size = 200

[2]
map_size = 400

[3]
map_size = 600

[4]
map_size = 800

[5]
map_size = 1000

[6]
map_size = 1200

[7]
map_size = 1400

[8]
map_size = 1600

[9]
map_size = 1800

[10]
map_size = 2000